/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SORT_H_RPCGEN
#define _SORT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXSORTSIZE 64

typedef int mytype;

struct sortobject {
	struct {
		u_int ss_len;
		mytype *ss_val;
	} ss;
};
typedef struct sortobject sortobject;

typedef sortobject returntype;

typedef sortobject parameter;

#define SORTPROG 22855
#define SORTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SORT 1
extern  returntype * sort_1(parameter *, CLIENT *);
extern  returntype * sort_1_svc(parameter *, struct svc_req *);
extern int sortprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SORT 1
extern  returntype * sort_1();
extern  returntype * sort_1_svc();
extern int sortprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_mytype (XDR *, mytype*);
extern  bool_t xdr_sortobject (XDR *, sortobject*);
extern  bool_t xdr_returntype (XDR *, returntype*);
extern  bool_t xdr_parameter (XDR *, parameter*);

#else /* K&R C */
extern bool_t xdr_mytype ();
extern bool_t xdr_sortobject ();
extern bool_t xdr_returntype ();
extern bool_t xdr_parameter ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SORT_H_RPCGEN */
