/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ass2.h"

bool_t
xdr_mytype (XDR *xdrs, mytype *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sortobject (XDR *xdrs, sortobject *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->ss.ss_val, (u_int *) &objp->ss.ss_len, MAXSORTSIZE,
		sizeof (mytype), (xdrproc_t) xdr_mytype))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_returntype (XDR *xdrs, returntype *objp)
{
	register int32_t *buf;

	 if (!xdr_sortobject (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_parameter (XDR *xdrs, parameter *objp)
{
	register int32_t *buf;

	 if (!xdr_sortobject (xdrs, objp))
		 return FALSE;
	return TRUE;
}
